// Define the base subjects that could be available across different grades
export const ALL_SUBJECTS = {
  MATHEMATICS: 'Math',
  SCIENCE: 'Science',
  ENGLISH: 'English',
  HINDI: 'Hindi',
  MARATHI: 'Marathi',
  GP: 'GP',
  CS: 'CS',
  ART: 'Art',
  BEE: 'BEE',
  PHYSICS: 'Physics',
  CHEMISTRY: 'Chemistry',
  DESIGN_TECH: 'Design and Tech',
  MEDIA_STUDIES: 'Media Studies',
  TRAVEL_TOURISM: 'Travel and Tourism',
  BUSINESS: 'Business'
} as const;

export type Subject = typeof ALL_SUBJECTS[keyof typeof ALL_SUBJECTS];

// Define grade levels
export const GRADE_LEVELS = {
  GRADE_1A: '1A',
  GRADE_1B: '1B',
  GRADE_1C: '1C',
  GRADE_1D: '1D',
  GRADE_2A: '2A',
  GRADE_2B: '2B',
  GRADE_2C: '2C',
  GRADE_3A: '3A',
  GRADE_3B: '3B',
  GRADE_3C: '3C',
  GRADE_4A: '4A',
  GRADE_4B: '4B',
  GRADE_4C: '4C',
  GRADE_5: '5',
  GRADE_6A: '6A',
  GRADE_6B: '6B',
  GRADE_7: '7',
  GRADE_8: '8',
  GRADE_9: '9',
  GRADE_10: '10',
  GRADE_A2: 'A2'
} as const;

export type GradeLevel = typeof GRADE_LEVELS[keyof typeof GRADE_LEVELS];

// Define subjects available for each grade level
export const GRADE_SUBJECTS: Record<GradeLevel, Subject[]> = {
  // Grades 1A-1D have the same subjects
  [GRADE_LEVELS.GRADE_1A]: [
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.SCIENCE,
    ALL_SUBJECTS.HINDI,
    ALL_SUBJECTS.MARATHI,
    ALL_SUBJECTS.GP,
    ALL_SUBJECTS.CS,
    ALL_SUBJECTS.ART
  ],
  [GRADE_LEVELS.GRADE_1B]: [
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.SCIENCE,
    ALL_SUBJECTS.HINDI,
    ALL_SUBJECTS.MARATHI,
    ALL_SUBJECTS.GP,
    ALL_SUBJECTS.CS,
    ALL_SUBJECTS.ART
  ],
  [GRADE_LEVELS.GRADE_1C]: [
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.SCIENCE,
    ALL_SUBJECTS.HINDI,
    ALL_SUBJECTS.MARATHI,
    ALL_SUBJECTS.GP,
    ALL_SUBJECTS.CS,
    ALL_SUBJECTS.ART
  ],
  [GRADE_LEVELS.GRADE_1D]: [
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.SCIENCE,
    ALL_SUBJECTS.HINDI,
    ALL_SUBJECTS.MARATHI,
    ALL_SUBJECTS.GP,
    ALL_SUBJECTS.CS,
    ALL_SUBJECTS.ART
  ],
  // Grades 2A-2C have the same subjects
  [GRADE_LEVELS.GRADE_2A]: [
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.SCIENCE,
    ALL_SUBJECTS.HINDI,
    ALL_SUBJECTS.MARATHI,
    ALL_SUBJECTS.GP,
    ALL_SUBJECTS.CS,
    ALL_SUBJECTS.ART
  ],
  [GRADE_LEVELS.GRADE_2B]: [
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.SCIENCE,
    ALL_SUBJECTS.HINDI,
    ALL_SUBJECTS.MARATHI,
    ALL_SUBJECTS.GP,
    ALL_SUBJECTS.CS,
    ALL_SUBJECTS.ART
  ],
  [GRADE_LEVELS.GRADE_2C]: [
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.SCIENCE,
    ALL_SUBJECTS.HINDI,
    ALL_SUBJECTS.MARATHI,
    ALL_SUBJECTS.GP,
    ALL_SUBJECTS.CS,
    ALL_SUBJECTS.ART
  ],
  // Grades 3A-3C have the same subjects
  [GRADE_LEVELS.GRADE_3A]: [
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.SCIENCE,
    ALL_SUBJECTS.HINDI,
    ALL_SUBJECTS.MARATHI,
    ALL_SUBJECTS.GP,
    ALL_SUBJECTS.CS,
    ALL_SUBJECTS.ART
  ],
  [GRADE_LEVELS.GRADE_3B]: [
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.SCIENCE,
    ALL_SUBJECTS.HINDI,
    ALL_SUBJECTS.MARATHI,
    ALL_SUBJECTS.GP,
    ALL_SUBJECTS.CS,
    ALL_SUBJECTS.ART
  ],
  [GRADE_LEVELS.GRADE_3C]: [
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.SCIENCE,
    ALL_SUBJECTS.HINDI,
    ALL_SUBJECTS.MARATHI,
    ALL_SUBJECTS.GP,
    ALL_SUBJECTS.CS,
    ALL_SUBJECTS.ART
  ],
  // Grades 4A-4C have the same subjects
  [GRADE_LEVELS.GRADE_4A]: [
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.SCIENCE,
    ALL_SUBJECTS.HINDI,
    ALL_SUBJECTS.MARATHI,
    ALL_SUBJECTS.GP,
    ALL_SUBJECTS.CS,
    ALL_SUBJECTS.ART
  ],
  [GRADE_LEVELS.GRADE_4B]: [
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.SCIENCE,
    ALL_SUBJECTS.HINDI,
    ALL_SUBJECTS.MARATHI,
    ALL_SUBJECTS.GP,
    ALL_SUBJECTS.CS,
    ALL_SUBJECTS.ART
  ],
  [GRADE_LEVELS.GRADE_4C]: [
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.SCIENCE,
    ALL_SUBJECTS.HINDI,
    ALL_SUBJECTS.MARATHI,
    ALL_SUBJECTS.GP,
    ALL_SUBJECTS.CS,
    ALL_SUBJECTS.ART
  ],
  // Grade 5
  [GRADE_LEVELS.GRADE_5]: [
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.SCIENCE,
    ALL_SUBJECTS.HINDI,
    ALL_SUBJECTS.MARATHI,
    ALL_SUBJECTS.GP,
    ALL_SUBJECTS.CS,
    ALL_SUBJECTS.ART
  ],
  // Grades 6A-6B have the same subjects with BEE added
  [GRADE_LEVELS.GRADE_6A]: [
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.SCIENCE,
    ALL_SUBJECTS.HINDI,
    ALL_SUBJECTS.MARATHI,
    ALL_SUBJECTS.GP,
    ALL_SUBJECTS.BEE,
    ALL_SUBJECTS.CS,
    ALL_SUBJECTS.ART
  ],
  [GRADE_LEVELS.GRADE_6B]: [
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.SCIENCE,
    ALL_SUBJECTS.HINDI,
    ALL_SUBJECTS.MARATHI,
    ALL_SUBJECTS.GP,
    ALL_SUBJECTS.BEE,
    ALL_SUBJECTS.CS,
    ALL_SUBJECTS.ART
  ],
  // Grades 7-10 have the same subjects with BEE
  [GRADE_LEVELS.GRADE_7]: [
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.SCIENCE,
    ALL_SUBJECTS.HINDI,
    ALL_SUBJECTS.MARATHI,
    ALL_SUBJECTS.GP,
    ALL_SUBJECTS.BEE,
    ALL_SUBJECTS.CS,
    ALL_SUBJECTS.ART
  ],
  [GRADE_LEVELS.GRADE_8]: [
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.SCIENCE,
    ALL_SUBJECTS.HINDI,
    ALL_SUBJECTS.MARATHI,
    ALL_SUBJECTS.GP,
    ALL_SUBJECTS.BEE,
    ALL_SUBJECTS.CS,
    ALL_SUBJECTS.ART
  ],
  [GRADE_LEVELS.GRADE_9]: [
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.SCIENCE,
    ALL_SUBJECTS.HINDI,
    ALL_SUBJECTS.MARATHI,
    ALL_SUBJECTS.GP,
    ALL_SUBJECTS.BEE,
    ALL_SUBJECTS.CS,
    ALL_SUBJECTS.ART
  ],
  [GRADE_LEVELS.GRADE_10]: [
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.SCIENCE,
    ALL_SUBJECTS.HINDI,
    ALL_SUBJECTS.MARATHI,
    ALL_SUBJECTS.GP,
    ALL_SUBJECTS.BEE,
    ALL_SUBJECTS.CS,
    ALL_SUBJECTS.ART
  ],
  // Grade A2 has different subjects
  [GRADE_LEVELS.GRADE_A2]: [
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.PHYSICS,
    ALL_SUBJECTS.CHEMISTRY,
    ALL_SUBJECTS.DESIGN_TECH,
    ALL_SUBJECTS.MEDIA_STUDIES,
    ALL_SUBJECTS.TRAVEL_TOURISM,
    ALL_SUBJECTS.BUSINESS,
    ALL_SUBJECTS.GP
  ]
};

// Helper function to get subjects for a specific grade
export function getSubjectsForGrade(grade?: GradeLevel): Subject[] {
  return GRADE_SUBJECTS[grade as GradeLevel] ?? [];
}

// Helper function to check if a subject is available for a grade
export function isSubjectAvailableForGrade(subject: Subject, grade?: GradeLevel): boolean {
  return GRADE_SUBJECTS[grade as GradeLevel]?.includes(subject) ?? false;
} 