// Define the base subjects that could be available across different grades
export const ALL_SUBJECTS = {
  MATHEMATICS: 'Mathematics',
  SCIENCE: 'Science',
  ENGLISH: 'English',
  SOCIAL_STUDIES: 'Social Studies',
  HISTORY: 'History',
  GEOGRAPHY: 'Geography',
  PHYSICS: 'Physics',
  CHEMISTRY: 'Chemistry',
  BIOLOGY: 'Biology',
  ENVIRONMENTAL_SCIENCE: 'Environmental Science',
  COMPUTER_SCIENCE: 'Computer Science',
  LITERATURE: 'Literature',
  LANGUAGE_ARTS: 'Language Arts',
  ALGEBRA: 'Algebra',
  GEOMETRY: 'Geometry',
  STATISTICS: 'Statistics',
  CIVICS: 'Civics'
} as const;

export type Subject = typeof ALL_SUBJECTS[keyof typeof ALL_SUBJECTS];

// Define grade levels
export const GRADE_LEVELS = {
  GRADE_1: '1',
  GRADE_2: '2',
  GRADE_3: '3',
  GRADE_4: '4',
  GRADE_5: '5',
  GRADE_6: '6',
  GRADE_7: '7',
  GRADE_8: '8',
  GRADE_9: '9',
  GRADE_10: '10',
  GRADE_11: '11',
  GRADE_12: '12'
} as const;

export type GradeLevel = typeof GRADE_LEVELS[keyof typeof GRADE_LEVELS];

// Define subjects available for each grade level
export const GRADE_SUBJECTS: Record<GradeLevel, Subject[]> = {
  [GRADE_LEVELS.GRADE_1]: [
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.SCIENCE,
    ALL_SUBJECTS.SOCIAL_STUDIES
  ],
  [GRADE_LEVELS.GRADE_2]: [
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.SCIENCE,
    ALL_SUBJECTS.SOCIAL_STUDIES
  ],
  [GRADE_LEVELS.GRADE_3]: [
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.SCIENCE,
    ALL_SUBJECTS.SOCIAL_STUDIES,
    ALL_SUBJECTS.LANGUAGE_ARTS
  ],
  [GRADE_LEVELS.GRADE_4]: [
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.SCIENCE,
    ALL_SUBJECTS.SOCIAL_STUDIES,
    ALL_SUBJECTS.LANGUAGE_ARTS
  ],
  [GRADE_LEVELS.GRADE_5]: [
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.SCIENCE,
    ALL_SUBJECTS.SOCIAL_STUDIES,
    ALL_SUBJECTS.LANGUAGE_ARTS
  ],
  [GRADE_LEVELS.GRADE_6]: [
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.SCIENCE,
    ALL_SUBJECTS.SOCIAL_STUDIES,
    ALL_SUBJECTS.LANGUAGE_ARTS,
    ALL_SUBJECTS.GEOGRAPHY
  ],
  [GRADE_LEVELS.GRADE_7]: [
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.SCIENCE,
    ALL_SUBJECTS.HISTORY,
    ALL_SUBJECTS.GEOGRAPHY,
    ALL_SUBJECTS.CIVICS
  ],
  [GRADE_LEVELS.GRADE_8]: [
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.SCIENCE,
    ALL_SUBJECTS.HISTORY,
    ALL_SUBJECTS.GEOGRAPHY,
    ALL_SUBJECTS.CIVICS
  ],
  [GRADE_LEVELS.GRADE_9]: [
    ALL_SUBJECTS.ALGEBRA,
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.BIOLOGY,
    ALL_SUBJECTS.HISTORY,
    ALL_SUBJECTS.GEOGRAPHY,
    ALL_SUBJECTS.COMPUTER_SCIENCE
  ],
  [GRADE_LEVELS.GRADE_10]: [
    ALL_SUBJECTS.GEOMETRY,
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.CHEMISTRY,
    ALL_SUBJECTS.HISTORY,
    ALL_SUBJECTS.LITERATURE,
    ALL_SUBJECTS.COMPUTER_SCIENCE
  ],
  [GRADE_LEVELS.GRADE_11]: [
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.PHYSICS,
    ALL_SUBJECTS.CHEMISTRY,
    ALL_SUBJECTS.BIOLOGY,
    ALL_SUBJECTS.COMPUTER_SCIENCE,
    ALL_SUBJECTS.STATISTICS
  ],
  [GRADE_LEVELS.GRADE_12]: [
    ALL_SUBJECTS.MATHEMATICS,
    ALL_SUBJECTS.ENGLISH,
    ALL_SUBJECTS.PHYSICS,
    ALL_SUBJECTS.CHEMISTRY,
    ALL_SUBJECTS.BIOLOGY,
    ALL_SUBJECTS.COMPUTER_SCIENCE,
    ALL_SUBJECTS.STATISTICS,
    ALL_SUBJECTS.ENVIRONMENTAL_SCIENCE
  ]
};

// Helper function to get subjects for a specific grade
export function getSubjectsForGrade(grade: GradeLevel): Subject[] {
  return GRADE_SUBJECTS[grade];
}

// Helper function to check if a subject is available for a grade
export function isSubjectAvailableForGrade(subject: Subject, grade: GradeLevel): boolean {
  return GRADE_SUBJECTS[grade].includes(subject);
} 