import { ASSIGNMENT_STATUS } from "@/constants/assignment-status";
import { AssignmentFormValues } from "@/lib/validations/assignment";

export const getDefaultValues = (): AssignmentFormValues => ({
  title: "",
  subject: "",
  grade: "",
  status: ASSIGNMENT_STATUS.DRAFT,
  artifact_type: "",
  month: new Date().toLocaleString('default', { month: 'long' }),
  is_team_work: false,
  is_original_work: true,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  is_parent: false,
  artifact_url: "",
  team_contribution: "",
  originality_explanation: "",
  selected_skills: [],
  skills_justification: "",
  pride_reason: "",
  creation_process: "",
  learnings: "",
  challenges: "",
  improvements: "",
  acknowledgments: "",
  submitted_at: new Date().toISOString(),
  verified_at: new Date().toISOString(),
  feedback: {},
  revision_history: [],
  youtubelinks: [{ url: "", title: "" }],
  files: [],
});